version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: blogs_api_node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      HOSTNAME: db
      JWT_SECRET: $JWT_SECRET
  db:
    container_name: blogs_api_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - $MYSQL_PORT:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD

networks:
  default:
    name: blogs_api_net